### ISSUE TITLE
Add the ability to move/look around while not register/logged in

### ISSUE THREAD

**Issue by suhaylhallim** [Chocorean/authmod#20]
Is it possible to add the ability to move around / look around while not registered / logged in? This ability should be able to be turned on and off in the config file as per admin preference. That way, admins can choose how to restrict the players. 
Either 
1. let them move around without being able to interact with the world i.e adventure mode
2. confine them to a building / room until registration and login
3. let have them register / login as it is now.

**Comment by Mcdostone** [comment]
your proposition is interesting ! with the use case 2, it can be tricky because players already connected can mine the building/room to let them escape!

**Comment by Chocorean** [comment]
> 
> 
> your proposition is interesting ! with the use case 2, it can be tricky because players already connected can mine the building/room to let them escape!

No, they currently cannot interract with anything until they `/login`



> 
> 
> Is it possible to add the ability to move around / look around while not registered / logged in? This ability should be able to be turned on and off in the config file as per admin preference. That way, admins can choose how to restrict the players.
> Either
> 
>     1. let them move around without being able to interact with the world i.e adventure mode
> 
>     2. confine them to a building / room until registration and login
> 
>     3. let have them register / login as it is now.

I do not see the point of this. I would go for a **no**, because if someone uses your account to move into a lava pool and disconnect, you will be mad when you will come back. It can only lead to sick jokes according to me.

Please tell me what do you think this will add to the mod, which btw is not supposed to be anything else than something who secure `online-mode=false`.
