### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by KaozKO** [Chocorean/authmod#43]
Good morning, i would like know if there is anyway that you dont have to log in every time you log in. Is there not a way to save the login and enter directly? Thanks

**Comment by Mcdostone** [comment]
Hi,
Do you mean like a `remember my password` feature?

**Comment by Chocorean** [comment]
I am not sure this is a good idea. That would likely mean we have to turn authmod into a client/server mod.
Otherwise, if the server has a « memory », it can only identify you with your ip address I believe, which means two things:
- the feature won’t work if your public IP address changes (and that can happen without you noticing it)
- The feature will obviously not work if you play somewhere else than home.
- Everyone behind your public IP address can login as yourself without your password. That includes siblings, friends, etc. It is limited to a few people, but you never know.

I also feel like it’s against the spirit of AuthMod. It is not meant to be practical, but safe for players playing on insecure servers.

But if a good idea comes in, I can reconsider it
